
 const data = [
     
         {"id":1,"name":"Mieruko-chan","describe":"Miko là một học sinh cao trung điển hình có cuộc sống đảo lộn khi cô đột nhiên bắt đầu nhìn thấy những con quái vật ghê rợn và gớm ghiếc. Mặc dù hoàn toàn vô cùng sợ hãi, Miko vẫn tiếp tục cuộc sống hàng ngày của mình, giả vờ không để ý đến nỗi kinh hoàng đang bao quanh cô. Cô ấy phải chịu đựng nỗi sợ hãi để giữ cho mình và người bạn Hana của cô ấy thoát khỏi nguy hiểm, ngay cả khi điều đó có nghĩa là phải đối mặt với điều tồi tệ nhất. Pha trộn giữa hài kịch và kinh dị, Mieruko-chan kể câu chuyện về một cô gái cố gắng đối phó với điều huyền bí bằng cách tỏ ra thờ ơ với nó.","rating":"9.7","episode":"12"},
         {"id":2,"name":"Mushoku Tensei: Isekai Ittara Honki Dasu","describe":"Phần 2 của tựa phim Mushoku Tensei","rating":"9.5","episode":"12"},
         {"id":3,"name":"The Flower We Saw That Day","describe":"Thời thơ ấu, nhóm bạn thân sáu người với luôn như hình với bóng. Tuy nhiên, khi lên cấp ba, họ lại trở nên xa cách. Jintan tự giam mình trong nhà. Anaru miễn cưỡng hòa nhập với hội bạn gái thời thượng. Yukiatsu và Tsuruko cùng học trường điểm có tiếng. Poppo bỏ học đi làm thêm, nuôi chí du lịch vòng quanh thế giới. Chỉ có Menma là chẳng thay đổi gì so với trước kia. Một ngày nọ, Menma đột nhiên xuất hiện trước mặt Jintan và nhờ cậu thực hiện một ước nguyện. Thế là nhóm sáu người lại tái hợp","rating":"9.8","episode":"11"},
         {"id":4,"name":"Sekai Saikō no Ansatsusha, Isekai Kizoku ni Tensei-suru","describe":"“Tôi sẽ sống cho chính mình!” Sát thủ vĩ đại nhất trên trái đất chỉ biết sống như một công cụ cho chủ nhân– cho đến khi họ quyết định giết ông. Được tái sinh bởi ân sủng của một nữ thần vào thế giới của kiếm và phép thuật, lần này ông ta có cơ hội để làm những điều khác đi, nhưng có một yêu cầu… Ông ta phải loại bỏ một anh hùng siêu mạnh, người nếu không bị ngăn chặn thì sẽ khiến thế giới diệt vong. Anh hùng được biết đến với cái tên Lugh Tuatha Dé, người khiến cả sát thủ bậc thầy cũng phải bất lực, nhất là vì những cô gái xinh đẹp mạnh mẽ luôn vây quanh anh ta. Dù là một sát thủ bậc thầy, nhưng ông ta sẽ xử trí thế nào tại thế giới chỉ có kiếm và phép thuật?","rating":"9.5","episode":"12"},
         {"id":5,"name":"Tensei Shitara Suraimu Datta Ken S2","describe":"Một anh chàng bị tên cướp đâm chết khi đi gặp đồng nghiệp cùng vợ chưa cưới của cậu ta. Khi đang thoi thóp trước khi chết, người đầy máu, anh ta nghe được một tiếng nói kỳ lạ. Giọng nói ấy chuyển thể sự tiếc nuối của anh chàng vì vẫn còn tân trước khi đi và ban cho anh ta chiêu thức đặc biệt [tiên nhân vĩ đại]. Liệu đây có phải là trò đùa?","rating":"9.8","episode":"23"}
        
 ]

